### PR TITLE
Perl 6 has been officially renamed Raku

### PR DESCRIPTION
**Pull request by MattOates**
The Perl 6 language has been officially renamed to Raku to avoid confusion with Perl 5. The current package/build is also a year out of date, which is significant given performance/cost of running any code. The Rakudo compiler now has the `raku` command alias too, going forwards this should be the default to align with the community best practices.

Im not entirely certain how polygott images are built or used by repl.it its possible the @nxadm `rakudo-pkg` is out of date and not maintained. If desirable I can move this to using the official Rakudo Star distribution of Rakudo, but this is not under package management. For example the latest release is 2020.01 repl.it currently has 2019.03.1 But I suspect this is simply a case of support was added a year ago and the package has not been updated?

### CODE REVIEW

**Comment by nxadm** [comment]
@MattOates, you seem to be misinformed about [rakudo-pkg](https://github.com/nxadm/rakudo-pkg) and Rakudo Star:

- rakudo-pkg is well maintained (by me) and it packages the latest monthly release *on the same day* Rakudo is released (most of the time). The latest releases are 2020.02.1 and 2020.01. Since the beginning, *every* Rakudo release has been built by rakudo-pkg. It also offer native repositories for easy installation. I am in close contact with the Raku team and help catch bugs before or during releases (packaging on 20 platforms is kind a smoke test).
- rakudo-pkg has the raku binary. It actually had it a long time before the upstream Rakudo sources add it to their build scripts. It also has zef so the user can install whatever module they need.
- Rakudo Star is not the official Rakudo distribution, but *a* distribution. This makes it less suitable for containers (one of my use cases).
- Rakudo Star does not offer precompiled native packages on Linux but compiles everything locally. I think this is not what Linux users expect when they want to try out Raku.
- The compiler in Rakudo Star is *not* a LTS release (there is no such thing in Rakudo), but just a regular release.
- In practice, Rakudo Star releases *yearly* (the latest releases were 2018.10 and 2019.03).

Feel free to have a look at the repo of contact me if you need more info.

**Comment by MattOates** [comment]
Thanks @nxadm this is why I tagged you. So the reason repl.it is behind is purely from a lack of rebuild of their image, and fixing the version they got from your repositories? I'm perhaps not as misinformed as you imagine, I've been a user for over a decade. Rakudo Star for all intents and purposes is a defacto LTS since about 2010, its a bit disingenuous to suggest otherwise, and packaging of R* is kind of an independent problem that could be just as easily solved by rakudo-pkg. Regardless of what anyone wants to say, bugs are resolved explicitly by the core team to meet that specific release that ends up as R*. You also don't get an R* without all the tests of the modules passing, or at least checked, which is typically a lot more rigorous than the regular monthly compiler release without this expectation.

**Comment by nxadm** [comment]
The reason rakudo-pkg exists is because rakudobrew was not recommended by core devs for the use by regular users and the Rakudo Star model does not match with my expectations. So we'll have to friendly disagree on that. For the record, I have no problem whatsoever if this project chooses to use Rakudo Star over rakudo-pkg, or if they prefer to use distro-dprovided packages or something else.  They all have their use case.

**Comment by dan-stowell** [comment]
Thank you, @MattOates, for submitting this! And thank you, @nxadm, for giving context on rakudo-pkg! My sincere apologies for letting this PR lay around so long.

We renamed perl 6 to raku with https://github.com/replit/polygott/pull/76 -- are there any changes you'd still like to make?

**Comment by dan-stowell** [comment]
I'm going to close this, @MattOates, since we've made the name change. If there are any improvements you'd like to see, feel free to reopen or open another PR!

**Comment by nxadm** [comment]
Thank you, @MattOates and @dan-stowell, for following up and solving this issue!

**Pull request closed without merging**
