### PR TITLE
Remove Chrome and Firefox

### PR DESCRIPTION
**Pull request by dan-stowell**
May need to deploy this to unblock replit.com in schools.

### CODE REVIEW

**Review by lhchavez — APPROVED** [review]
🇫

this will break a bunch of selenium repls (as well as the PulseAudio demo, but i can live with that), but may this be in the name of unblockage.

**Comment by hackermondev** [comment]
sad

**Comment by firefish111** [comment]
g

**Comment by RayhanADev** [comment]
@lhchavez @dan-stowell
I very much disagree with this change. Many people use WebBot in Python (best I can think off the top of my head) and other things that depend on usage of Selenium. Students abusing Replit is a school's problem, and *downgrading* Replit should **never** be the solution.

**Possible (Better) Solution**:
Check a user for the `student` role or whether they are a member of a `Teams for School` team and restrict usage of the browsers if they are. Accounts that are not shouldn't be restricted in access to web browsers due to the amount of projects that depend on them.

**Comment by hackermondev** [comment]
u should probably post that on feedback

**Comment by RayhanADev** [comment]
> u should probably post that on feedback

There's a feedback board for Polygott specifically? It's not like they merged this yet so I dropped a comment.

**Comment by dbarnes18** [comment]
Suggestion from Canny that I think would be relevant here.

https://replit.canny.io/general-feedback/p/allow-paying-repl-users-to-utilize-proxies

Screenshot 2021-05-30 at 13 21 19

**Comment by Grify** [comment]
> @lhchavez @dan-stowell
> I very much disagree with this change. Many people use WebBot in Python (best I can think off the top of my head) and other things that depend on usage of Selenium. Students abusing Replit is a school's problem, and _downgrading_ Replit should **never** be the solution.
> 
> **Possible (Better) Solution**:
> Check a user for the `student` role or whether they are a member of a `Teams for School` team and restrict usage of the browsers if they are. Accounts that are not shouldn't be restricted in access to web browsers due to the amount of projects that depend on them.
> 
> Let me know what you think.

I completely agree with @RayhanADev, the product shouldn't be measurably worsened to appease anybody, not investors and certainly not schools. I understand that education is crucial for repl.it, but it goes the other direction too, repl.it access is crucial for schools. Although there will always be a few questionable people who use technology for bad, such is inevitable, and it shouldn't be used as an excuse to remove or limit technology's availability.

**Comment by dan-stowell** [comment]
We are relying more and more on nix to install packages into repls: https://docs.replit.com/repls/nix

No need to remove anything from Polygott at this point.

**Pull request closed without merging**
