### PR TITLE
upgrade julia to 1.4.1

### PR DESCRIPTION
**Pull request by dan-stowell**
This is a copy of https://github.com/replit/polygott/pull/89 from @logankilpatrick - I wanted to pick up the latest build fixes on master.

### CODE REVIEW

**Comment by logankilpatrick** [comment]
This is great! Thank you!

**Review by logankilpatrick — APPROVED** [review]
Thank you again!

**Comment by logankilpatrick** [comment]
@dan-stowell Anyway we can get this merged and then I can open another PR to bump to 1.5.3?

**Comment by logankilpatrick** [comment]
@dan-stowell bumping this again

**Comment by logankilpatrick** [comment]
@dan-stowell perhaps I can be made a codeowner of the Julia.toml file to speed up future changes as well?

**Comment by logankilpatrick** [comment]
@amasad any chance we can get this taken care of? It's been a 3+ month journey :)

**Comment by dan-stowell** [comment]
Closing in favor of https://github.com/replit/polygott/pull/220

**Pull request closed without merging**
