### PR TITLE
Upgrade Nodejs to 14.x

### PR DESCRIPTION
**Pull request by sergeichestakov**
bc ppl want

Twitter Node

### CODE REVIEW

**Comment by dan-stowell** [comment]
Love your spirit always, @sergeichestakov ! Right now, the nodejs language uses a non-polygott Docker image. We should either

1) upgrade the non-polygott Docker image to node 14.x, then migrate to polygott node
2) migrate to polygott node on node 12.x, then upgrade the polygott node to 14.x

**Comment by masad-frost** [comment]
@dan-stowell We should also probably give a heads-up to people as Node 12->14 might break some apps

**Comment by sergeichestakov** [comment]
Aww man totally forgot Node wasn't on polygott 🤦‍♂️ 

I'm leaning towards the former. Think it'd be nice to ship this so that polygott is on the latest Node version anyways and then follow up with updating the Node image to 14 and eventually moving it to polygott.

+1 this will be a breaking change for some people - not sure the best way to go about it

**Comment by masad-frost** [comment]
Yeah I agree, option 1 seems like it gives us immediate wins. Would be nice if bash repls had node 14 ASAP so we can point people who really want it there.

**Review by masad-frost — APPROVED** [review]
I wonder if we need to upgrade jest, prettier, and globally installed packages.

**Pull request merged**
